In [2]:
import pandas as pd

In [3]:
dataframe = pd.read_json("iris.json")

In [4]:
dataframe

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [5]:
dataframe.head(100)

    sepal.length  sepal.width  petal.length  petal.width     variety
0            5.1          3.5           1.4          0.2      Setosa
1            4.9          3.0           1.4          0.2      Setosa
2            4.7          3.2           1.3          0.2      Setosa
3            4.6          3.1           1.5          0.2      Setosa
4            5.0          3.6           1.4          0.2      Setosa
..           ...          ...           ...          ...         ...
95           5.7          3.0           4.2          1.2  Versicolor
96           5.7          2.9           4.2          1.3  Versicolor
97           6.2          2.9           4.3          1.3  Versicolor
98           5.1          2.5           3.0          1.1  Versicolor
99           5.7          2.8           4.1          1.3  Versicolor

[100 rows x 5 columns]

In [9]:
dataframe_2 = pd.json_normalize(dataframe)
dataframe_2

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]