In [3]:
import pandas as pd
date_time = pd.DatetimeIndex(["1/1/2020 10:00:00+00:00", "2/1/2020 11:00:00+00:00"])
df = pd.read_csv('titanic.csv')
#df.index = date_time
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.groupby(['Pclass','Sex'])['Age'].mean()

Pclass  Sex
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64

In [5]:
df.groupby(['Sex','Age'])['Fare'].mean()

Sex     Age
female  0.75     19.258300
        1.00     13.437500
        2.00     43.245833
        3.00     31.327100
        4.00     22.828340
                   ...
male    70.00    40.750000
        70.50     7.750000
        71.00    42.079200
        74.00     7.775000
        80.00    30.000000
Name: Fare, Length: 145, dtype: float64

In [6]:
filter_groupby = (lambda x:x+10)
df['Fare'].apply(filter_groupby)

0      17.2500
1      81.2833
2      17.9250
3      63.1000
4      18.0500
        ...
886    23.0000
887    40.0000
888    33.4500
889    40.0000
890    17.7500
Name: Fare, Length: 891, dtype: float64

In [7]:
date = pd.date_range(start = '01/01/2026',end='31/12/2026',freq='D')

#df.resample('W').count()

In [8]:
for name in df['PassengerId'][0:20]:
    print(name)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

In [9]:
[name for name in df['PassengerId'][0:12]]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [10]:
def uppercase(x:str)->str:
    return x.upper()

df['Name'].apply(uppercase)[0:21]

0                               BRAUND, MR. OWEN HARRIS
1     CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                HEIKKINEN, MISS. LAINA
3          FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                              ALLEN, MR. WILLIAM HENRY
5                                      MORAN, MR. JAMES
6                               MCCARTHY, MR. TIMOTHY J
7                        PALSSON, MASTER. GOSTA LEONARD
8     JOHNSON, MRS. OSCAR W (ELISABETH VILHELMINA BERG)
9                   NASSER, MRS. NICHOLAS (ADELE ACHEM)
10                      SANDSTROM, MISS. MARGUERITE RUT
11                             BONNELL, MISS. ELIZABETH
12                       SAUNDERCOCK, MR. WILLIAM HENRY
13                          ANDERSSON, MR. ANDERS JOHAN
14                 VESTROM, MISS. HULDA AMANDA ADOLFINA
15                     HEWLETT, MRS. (MARY D KINGCOME)
16                                 RICE, MASTER. EUGENE
17                         WILLIAMS, MR. CHARLES EUGENE
18    VANDER PLANKE, MRS. JULIUS (EMELIA MARIA VANDE...
19                              MASSELMANI, MRS. FATIMA
20                                 FYNNEY, MR. JOSEPH J
Name: Name, dtype: object

In [11]:
df_1 = df
df_2 = pd.read_csv('titanic.csv')
df_2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
#df_1.merge(df_2,right_on="Pclass",left_on="Pclass")
df_1.merge(df_2,on="Pclass")

,PassengerId_x,Survived_x,Pclass,Name_x,Sex_x,Age_x,SibSp_x,Parch_x,Ticket_x,Fare_x,...,Survived_y,Name_y,Sex_y,Age_y,SibSp_y,Parch_y,Ticket_y,Fare_y,Cabin_y,Embarked_y
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,...,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,...,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,...,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,...,0,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,...,0,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321588,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,...,0,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
321589,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,...,0,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
321590,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,...,0,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
321591,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,...,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
321592,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,...,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
pd.concat([df_1,df_2],axis=0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q