In [2]:
import pandas as pd

In [3]:
dataframe = pd.read_excel('Cola.xlsx')

In [4]:
dataframe.T

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
Data provided by SimFin,NaN,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 1,NaN,NaN,in million USD,NET OPERATING REVENUES,Cost of goods sold,Gross Profit,"Selling, general and administrative expenses",Other operating charges,Operating Income,Interest income,...,Purchases of stock for treasury,Dividends,Other financing activities,Net cash provided by (used in) financing activ...,Cash Provided by (Used in) Operating Activitie...,Effect of exchange rate changes on cash and ca...,Cash Provided by (Used in) Investing Activitie...,Cash Provided by (Used in) Financing Activitie...,Net Cash Provided by (Used in) Discontinued Op...,Net increase (decrease) during the year
Unnamed: 2,NaN,NaN,FY '09,30990,11088,19902,11358,313,8231,249,...,-1518,-3800,-2,-2293,NaN,576,NaN,NaN,NaN,2320
Unnamed: 3,NaN,NaN,FY '10,35119,12693,22426,13194,819,8413,317,...,-2961,-4068,50,-3465,NaN,-166,NaN,NaN,NaN,1496
Unnamed: 4,NaN,NaN,FY '11,46542,18215,28327,17422,732,10173,483,...,-4513,-4300,45,-2234,NaN,-430,NaN,NaN,NaN,4286
Unnamed: 5,NaN,NaN,FY '12,48017,19053,28964,17738,447,10779,471,...,-4559,-4595,100,-3347,NaN,-255,NaN,NaN,NaN,-4361
Unnamed: 6,NaN,NaN,FY '13,46854,18421,28433,17310,895,10228,534,...,-4832,-4969,17,-3745,NaN,-611,NaN,NaN,NaN,1972
Unnamed: 7,NaN,NaN,FY '14,45998,17889,28109,17218,1183,9708,594,...,-4162,-5350,-363,-3631,NaN,-934,NaN,NaN,NaN,-1456
Unnamed: 8,NaN,NaN,FY '15,44294,17482,26812,16427,1657,8728,613,...,-3564,-5741,251,-5113,0,-878,0,0,0,-1649
Unnamed: 9,NaN,NaN,FY '16,41863,16465,25398,15262,1510,8626,642,...,-3681,-6043,79,-6545,0,-6,0,0,0,1246
Unnamed: 10,NaN,NaN,FY '17,35410,13255,22155,12654,1902,7599,677,...,-3682,-6320,-91,-7409,111,241,-58,-38,15,-2477
Unnamed: 11,NaN,NaN,FY '18,31856,11770,20086,10307,1079,8700,682,...,-1912,-6644,-243,-10552,307,-262,-421,205,91,2945

In [5]:
dataframe.loc[0:10:]

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770
5,NaN,Gross Profit,19902,22426,28327,28964,28433,28109,26812,25398,22155,20086
6,NaN,"Selling, general and administrative expenses",11358,13194,17422,17738,17310,17218,16427,15262,12654,10307
7,NaN,Other operating charges,313,819,732,447,895,1183,1657,1510,1902,1079
8,NaN,Operating Income,8231,8413,10173,10779,10228,9708,8728,8626,7599,8700
9,NaN,Interest income,249,317,483,471,534,594,613,642,677,682
10,NaN,Interest expense,355,733,417,397,463,483,856,733,841,919

In [6]:
dataframe

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770
...,...,...,...,...,...,...,...,...,...,...,...,...
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945

In [7]:
dataframe1 = pd.DataFrame([["HEllo", "World"],
                           ["Hi", "There"]],
                           ["People","always"])

In [ ]:
dataframe1.T

  People always
0  HEllo     Hi
1  World  There

: